### ISSUE TITLE
Provide description on how to drive synthetic load

### ISSUE THREAD

**Issue by metmajer** [redhat-reactive-msa/redhat-reactive-msa#3]
Hi and thanks for providing this app! I am curious to learn how to best drive synthetic load to the msa? A simple GET request to, e.g., `/halo` or `/halo/chain`, doesn't seem to do the trick. Thanks!

**Comment by cescoffier** [comment]
Sending multiple requests to "/api" on the frontend server will invoke all the services. 

It's the only HTTP endpoint to call the services. The other invocations use the vert.x event bus, and so you would need a vert.x event bus client.

**Comment by metmajer** [comment]
Thanks!
